const mongoose = require('mongoose');

const VALID_EVENT_TYPES = [
  'log_media',
  'rate',
  'review',
  'status_change',
  'list_add',
  'follow',
  'search',
  'view_media_page',
  'onboarding_complete',
  // Social post events
  'post_create',
  'post_like',
  'post_comment',
  'post_repost',
  'post_bookmark',
];

const eventSchema = new mongoose.Schema({
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  event_type: {
    type: String,
    enum: VALID_EVENT_TYPES,
    required: true,
  },
  // nullable — not all events are tied to a specific title
  canonical_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CanonicalMedia',
    default: null,
  },
  // Flexible per-event metadata (e.g. { query: 'naruto', results_count: 12 })
  metadata: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
  },
  // UUID generated by the client, persisted per browser session
  session_id: {
    type: String,
    default: null,
  },
  created_at: {
    type: Date,
    default: Date.now,
    index: true,
  },
});

eventSchema.index({ user_id: 1, created_at: -1 });
eventSchema.index({ event_type: 1, created_at: -1 });
eventSchema.index({ canonical_id: 1, event_type: 1, created_at: -1 });

module.exports = mongoose.model('Event', eventSchema);
module.exports.VALID_EVENT_TYPES = VALID_EVENT_TYPES;
